-- Seed de 527 ejercicios para la tabla "Ejercicio"
-- Pegar en Supabase SQL Editor y ejecutar

INSERT INTO "Ejercicio" (id, nombre, patron, activo, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'Peso Muerto con Trap Bar', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto Sumo convencional', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto Rumano', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto rumano asimetrico', 'Cadena Posterior', true, NOW(), NOW()),
(gen_random_uuid(), 'Patada de gluteos', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion de cadera en fitball', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion de cadera', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion de Cadera a una pierna', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Caminatas de Isquios', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de Isquio en Fitball', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de Cadera Elevado', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto con Kettlebell', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Swing con Kettlebell', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Swing con kettlebell a un brazo', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos horizontales', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos desde Rodillas', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto Unipodal (B stance)', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla con barra', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Puente de gluteo isometrico', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de Cadera con Barra', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press con mancuernas en puente', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Press unilateral en puente', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto rumano sumo', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto rumano asimetrico con mancuernas', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press plano unilateral', 'Empuje Horizontal 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto Rumano con Mancuernas', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto Rumano con deficit', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso Muerto bulgaro', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con deficit', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Buenos Días con Barra', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Búlgara', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Búlgara con Salto', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Split con mancuernas', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla de Copa', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos al Cajón', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Desaceleracion desde cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto contra movimiento desde cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Subida al cajon unipodal', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Desaceleracion con cambio de direccion', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto a cajon unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de Cadera con Banda Redonda', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto contramovimiento a cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Desaceleracion desde cajon mas salto', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera unipodal con pelota', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto desde cajon enfasis vertical', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto en valla mas salto a cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de Cadera Elevado Unipodal', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto MB mas vallas mas salto a cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto en valla unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto lateral', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto bipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto lateral unipodal en conos', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha lateral mas elevacion', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Rock back de aductores', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Búlgara con Déficit', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'ISO push BB flor press', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof vertical', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof a bisagra', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla de Pulso A', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Step Down', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Subidas al cajon con carga', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada atras', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla tempo 5 3 1', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla frontal', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla zombie', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Skater', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Cosaco con Trapo', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla de Zercher', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla superman', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Good morning zercher', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada atras zercher', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla con disco', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla a Cajón (Box squat)', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla de Arranque', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada caminando', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Militar con Barra', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Thruster con mancuernas', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Militar con Mancuernas', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Plano (Bench press)', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexiones de brazos regresion', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexiones de brazos en paralelas', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexiones de brazos', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexiones de brazos Inclinadas', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexiones de brazos Declinadas', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl nordico invertido mas press', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl nordico invertido', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Press javalina', 'Empuje Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Cargada de potencia a cajon', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Aperturas con Mancuernas disociadas', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Fondos en banco', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones toracicas en cuadrupedia', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones toraco dorsal semi arrodillado', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones toracicas en bisagra', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones toracicas sobre rodillas', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad dorsal en cuadrupedia', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Aperturas con Mancuernas', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a 1 brazo', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas supinas', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo invertido 45°', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo prono en TRX', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo neutro en Trx', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo supino', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Gato bueno Gato malo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo con Barra', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad escapular', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad dinamica de psoas', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad dinamica de isquio', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo Horizontal con Mancuernas', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo neutro en TRX sobre cajon', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de isquio/cadera', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexion extension de rodilla', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de tobillo con carga', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rueda abdominal', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha abdominal alejada', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Bird dog avanzado', 'Estabilidad Posterior', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto convencional', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de tobillo con banda', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha en Fitball', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'RollOut en Fitball', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Revolver la Olla', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha con rotacion', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Bird Dog', 'Anti-Flexion', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha Lateral con Rodilla Apoyada', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Hollow', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha Lateral Glúteo Medio', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Partida desde banco mas Salto con rotacion a cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'TB tiron alto', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Pallof TB', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Pallof con carga', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto al cajón rotacional sentado', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto al cajon Desde sentado', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'CM horizontal box jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'CM rotacional box jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Bicho muerto 3 1', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Bicho muerto doble', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Bicho muerto', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexion de brazos reactivo', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Arm kb', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha en fitball con impulso', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha con los codos extendidos', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Halo', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Halo en cuclillas', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'ISO push BB 1 leg squat', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha Lateral Copenhague', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Dragon Flag excéntrico', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), '2P CCM vertical asistido', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), '2P vertical CC reactivo', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof (anti extensión a anti lateral)', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof en estocada', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada atras con mancuerna', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla frontal con elevacion de talon', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion en plancha lateral', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Patada lateral gluteo', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Posicion de sentadilla', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), '8 kb', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Estiramiento dinamico cadena posterior', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha de granjero unilateral', 'Transporte', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha de granjero', 'Transporte', true, NOW(), NOW()),
(gen_random_uuid(), 'Arranque dinamico con mancuerna', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Arranque con mancuerna', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada isometrica sobre disco', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada isometrica talon elevado', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones toracias 90-90', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo en ladmine', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Estiramiento de gluteo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps en trx', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Seal jack', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Frog Pump', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla a 1 pierna a cajon', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla a 1 pierna pistol', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de isquio con banda', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Abduccion con banda', 'Banda', true, NOW(), NOW()),
(gen_random_uuid(), 'Pull Apart', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Regresion de peso muerto a 1 pierna', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto unipodal kb', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Mountain climbers', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Mountain climbers semi circle', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'In and out', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Bisagra de Cadera con Bastón', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha jack', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha con rotacion lateral', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Clean and jerk ladmine', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Arranque en ladmine', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto en ladmine', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo en ladmine toma vikinga', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla en ladmine', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press vikingo', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera con Abducción', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof en estocada rotacion', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof mas skipping', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Bisagra de cadera en fitball', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Regresion peso muerto unipodal', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Regresion peso muerto unipodal con band', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad activa de isquio', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada caminando enfoque en gluteo', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Push press', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Tall clean', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Lateral hop', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Skater jump al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Tall power jerk', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de hombros en MB', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Preventivo de espalda', 'Preventivos', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de cadera 90/90', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto con banda de resistencia', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto lateral + salto al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Split jump + salto al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas a un brazo', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Seal row', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Core en puente', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas prono', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas tras nuca', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Dragon flag leg', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Dragon flag truck', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Dragon flag negative', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Dragon flag pulso', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Swing T handle', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto toma de arranque', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Stradle lift', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Aperturas de pecho en TRX', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pecho en TRX', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Press frances en TRX', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl femoral en TRX', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha dinamica supina', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha supina', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha alta supina', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha baja supina', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Press de banco con mancuernas', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera a una pierna mas press', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera mas press', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Press z dumbell', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha quito apoyos', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha toque de hombros', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha mas empuje', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha lateral + remo', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha alta + traslado', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha posicion de oso + traslado', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Swing de la cabra kb', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Vuelos frontal con disco', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Vuelos frontales con mancuerna', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Vuelos laterales', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha lateral gluteo medio', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Fondos en banco regresion', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Larseen press', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Frog pump', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion de cadera elevado kb', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Elevacion de cadera unipodal elevado', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera con banda', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto piernas rigidas', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Cargada de potencia colgado', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Envion de potencia', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto vertical con banda de resistencia', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad dinamica de isquio en un apoyo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha copenhague', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha copenhague regresion', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Camino a la plancha', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha lateral aductor', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Masaje foam roll aductor', 'Liberacion Miofascial', true, NOW(), NOW()),
(gen_random_uuid(), 'Masaje foam roll tensor de la fascia', 'Liberacion Miofascial', true, NOW(), NOW()),
(gen_random_uuid(), 'Masaje foam roll isquio', 'Liberacion Miofascial', true, NOW(), NOW()),
(gen_random_uuid(), 'Bicho muerto con disco', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Bicho muriendo con disco', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Gemelos con barra', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Patron respiratorio posicion bebe', 'Respiratorio', true, NOW(), NOW()),
(gen_random_uuid(), 'Patron respiratorio progresion', 'Respiratorio', true, NOW(), NOW()),
(gen_random_uuid(), 'Patron respiratorio acostado', 'Respiratorio', true, NOW(), NOW()),
(gen_random_uuid(), 'Bisagra de cadera', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Hiperextension de cadera prono', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Puente bilateral con tension', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo en dos apoyos', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo invertido a 45 supino', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo prono regresion (chin up)', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo invertido prono (chin up)', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo invertido sobre cajon', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo con banda unilateral', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps alternados', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps martillo', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo con barra toma prono', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo con barra toma supina', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps con barra', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Acoples paralelos', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de isquio excentrico', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Levantada turca con kb', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Hike pass mas swing', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Hike pass kb', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'BK clean pause', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Cat cow', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Impulso mas salto al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Seal row peso corporal', 'Peso Corporal', true, NOW(), NOW()),
(gen_random_uuid(), 'Recepcion lateral mas salto', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto a una pierna', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Clean con kb', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Swing frontal', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Patrones rotacionales kb', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Progresion roll out', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Roll out declinado', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Roll out con fitball', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Tgu con mancuerna', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de tobillo sobre cajon', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Molino alto', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Molino completo', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto con carga', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento MB Horizontal', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento frontal arrodillado MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento rotacional MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento bisagras MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Halo mas bisagras con disco', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Movilidad de hombros con banda', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Giros rusos', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Abdominales con carga', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Hollow dinamico', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo pelvis alineada', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo sobre banco', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press militar posicion de caballero', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press militar posicion dividida', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press militar alternado', 'Empuje Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Extension isometrica en banco rumano', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Cars de cadera', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla isometrica a una pierna', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla isometrica', 'Isometrico', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha prona en 3 apoyos', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Cars de tobillo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Cars de columna', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla frontal asimetrica', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo pendlay', 'Traccion Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocadas con barra', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps con barra EZ', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Subidas al cajon a una pierna', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha granjero zercher', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexion extension de tobillo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotacion interna de tobillo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Gato contento-enojado de tobillo', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotacion externa de hombro', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Face pull', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Liberacion miofascial plantar', 'Liberacion Miofascial', true, NOW(), NOW()),
(gen_random_uuid(), 'Press unilateral', 'Empuje Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Spiderman Alto', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotacion Toracica Foam roll', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotacion Toracica Con baston', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Cars de Hombros', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Push up + TH', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto Asimetrico', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Triceps en Polea', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones en Polea', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof antiextension', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto Horizontal Caida unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada ISO Catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Power jerk', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo Ladmine', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Glúteos isquiotibiales sobre banco', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas pliometricas', 'Traccion Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones con disco sobre Fitball', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de cadera asimetrico', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'CMJ Arms Free', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto SPLIT', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto rotacional al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Primer paso mas Salto al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos de aproximacion', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto caida unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'De Rodilla mas salto', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto en profundidad', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto escalonado al cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto lateral hacia el soporte', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Dominadas toma prona + lanz de MB sobre cabeza', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press de banca + lanz de MB', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press de banca + ext de BB con impulso', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Subidas al banco + subidas reactiva con salto', 'Rodilla Dominante 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto rumano 1P + peso muerto MB 1P + lanz', 'Cadera Dominante 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con barra + sentadilla bulgara con salto', 'Rodilla Dominante 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada lateral con barra + bound', 'Rodilla Dominante 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla + press de H + lanz vertical de MB', 'Rodilla Dominante 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Empuje de fuerza con barra + saltar y alcanzar', 'Rodilla Dominante 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento al piso desde cabeza con MB 2B', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento laterales al piso desde cabeza con MB 2B', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamientos laterales al piso desde cabeza con MB 2B sentado', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla + lanzamientos hacia arriba por encima de cabeza', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de pecho con MB en posicion supina', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de pecho con MB arrodillado alt', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de pecho con MB + extension de cadera', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento a 1B con MB arrodillado alterno', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento a 1B con MB parado alterno', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de pecho con MB de pie', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento a 1B con MB arrodillado', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de pecho con MB arrodillado desde posicion elevada', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento rotatorio con MB de pie', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento lateral con MB arrodillado alterno', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento por encima de la cabeza con MB en posicion supina sobre FB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento lateral con MB arrodillado', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Posicion partida alta + lanzamiento de pecho con MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Aceleracion + lanzamiento de pecho con MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Desplazamiento lateral + freno + cambio de direccion + lanz de MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto rumano a 1P + lanz MB', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de arriba a bajo arrodillado alterno', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de arriba a bajo parado alterno', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto a 1P con caida de MB', 'Cadera Dominante 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento hacia el piso desde cabeza arrodillado', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla con barra + salto sobre box', 'Rodilla Dominante 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla en maquina Smith', 'Cadena Anterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Split en maquina Smith', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara en maquina Smith', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Press de banca en maquina Smith', 'Empuje Horizontal 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Aperturas en polea', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo de pie en polea 1B', 'Traccion Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Dorsales en maquina prono', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Dorsales en polea supino', 'Traccion Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Extensiones laterales en polea', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Vuelo lateral en polea', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de biceps en polea', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de isquio en maquina', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Curl de isquio en maquina 2-1', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Press de pecho en maquina (peck deck)', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Cuadriceps en maquina', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Cuadriceps en maquina + isometria en extension', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Peck deck (Aperturas)', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Prensa horizontal 2P', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Prensa a 45° 2P', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Prensa a 45° 1P', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla con barra Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Puente de gluteos Iso Switch', 'Iso Switch', true, NOW(), NOW()),
(gen_random_uuid(), 'Isquio en cajon Iso Catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Puente de Gluteos Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo en TRX Iso Catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo en TRX Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Aterrisaje de un brazo iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexion de brazos Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Caida de rodilla Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Flexion de brazos declinadas Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento mas drill', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto desde rodilla mas lanzamiento', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento horizontal', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Primer paso mas lanzamiento', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento 1 Brazo', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento patron rotacional', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Cars de cadera sobre rack', 'Movilidad', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento de bala en ladmine', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Rack chin plyo', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Pull up plyo', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Push up plyo sobre discos', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Push up plyo', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Push up plyo lateral', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'RDL Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla split Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Iso push desde tobillo', 'Iso Push', true, NOW(), NOW()),
(gen_random_uuid(), 'Push up iso catch bodyweight', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo 1b Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Una sola pierna Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto concentrico', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Tuck jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'CMJ jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'CMJ squat jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Drop Jump', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto con caida a una pierna', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto bipodal desde tobillo', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con resistencia lateral', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara de arranque', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara pulso', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara goblet', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara OH 1b', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara sobre hombros', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara OH DB', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara OH con disco', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara contralateral', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara homolateral', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara 1b sobre hombro', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara apoyo metatarso', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con deficit DB', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara antiflexion', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con salto', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla bulgara con disco', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Cargada de potencia', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada Iso hold', 'Iso Hold', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto unipodal con barra', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Vuelos posteriores DB', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Pull up con banda de resistencia', 'Accesorios MMSS', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos bipodales con banda de resistencia', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Press en ladmine posicion estocada', 'Empuje Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Press ladmine apoyos asimetricos', 'Empuje Vertical 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'RDL en ladmine', 'Cadena Posterior 2P', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto unipodal en ladmine', 'Cadena Posterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo 1b en ladmine', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Drop Jump Caida Unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Sentadilla Bulgara Excentrica acentuada', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Lanzamiento Horizontal Isquio Activo', 'Lanzamientos', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Militar de rodillas', 'Empuje Vertical 2B', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha Frontal + Vuelo lateral', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha Granjero Zercher', 'Anti-Flexion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press Pallof estocada', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof + paso de aceleracion', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof marcha', 'Anti-Flexion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof apoyos asimetricos', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof de rodillas', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof + Skipping', 'Anti-Rotacion', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada hacia atras + pallof', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo + peso muerto unipodal Iso catch', 'Iso Catch', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha alta dinamica con cambio de apoyos', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Press pallof Dinamico', 'Anti-Flexion Lateral', true, NOW(), NOW()),
(gen_random_uuid(), 'Rotaciones en ladmine', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a un brazo en puente TRX', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Plancha frontal + lateral', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha Granjero + Press', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Marcha Granjero Con mancuernas', 'CORE', true, NOW(), NOW()),
(gen_random_uuid(), 'Acoples paralelos o cruzados', 'Anti-Extension', true, NOW(), NOW()),
(gen_random_uuid(), 'Arranque Frances', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Cargada Frances', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Segundo tiempo tijera', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Segundo tiempo tijera trasnuca', 'DLP', true, NOW(), NOW()),
(gen_random_uuid(), 'Remo a 1 Brazo en cuadrupedia', 'Traccion Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Catch Unipodal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Press en Banco plano unilateral', 'Empuje Horizontal 1B', true, NOW(), NOW()),
(gen_random_uuid(), 'Estocada lateral en ladmine', 'Cadena Anterior 1P', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto lateral en vallas', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Primer paso + Salto a cajón', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos Reactivos a cajón', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Drop jump a Cajon', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Drop Jump + Salto horizontal + Salto en diagonal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Saltos horizontal reactivo', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Drop jump + Salto horizontal', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Bounds alternos', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Hops en desplazamiento', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Salto bipodal + Salto en Altura', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Locomotive plyometric', 'Saltos', true, NOW(), NOW()),
(gen_random_uuid(), 'Tobillo iso push', 'Accesorios MMII', true, NOW(), NOW()),
(gen_random_uuid(), 'Sprint 10 Metros', 'Sprint', true, NOW(), NOW()),
(gen_random_uuid(), 'Peso muerto ISO push', 'Iso Push', true, NOW(), NOW());