import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const ejercicios = [
  { nombre: 'Peso Muerto con Trap Bar', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso Muerto Sumo convencional', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso Muerto Rumano', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso muerto rumano asimetrico', patron: 'Cadena Posterior' },
  { nombre: 'Patada de gluteos', patron: 'Accesorios MMII' },
  { nombre: 'Elevacion de cadera en fitball', patron: 'Accesorios MMII' },
  { nombre: 'Elevacion de cadera', patron: 'Cadena Posterior 2P' },
  { nombre: 'Elevacion de Cadera a una pierna', patron: 'Cadena Posterior 1P' },
  { nombre: 'Caminatas de Isquios', patron: 'Accesorios MMII' },
  { nombre: 'Curl de Isquio en Fitball', patron: 'Accesorios MMII' },
  { nombre: 'Empuje de Cadera Elevado', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso Muerto con Kettlebell', patron: 'Cadena Posterior 2P' },
  { nombre: 'Swing con Kettlebell', patron: 'Cadena Posterior 2P' },
  { nombre: 'Swing con kettlebell a un brazo', patron: 'Accesorios MMII' },
  { nombre: 'Saltos horizontales', patron: 'Saltos' },
  { nombre: 'Saltos desde Rodillas', patron: 'Saltos' },
  { nombre: 'Peso Muerto Unipodal (B stance)', patron: 'Cadena Posterior 1P' },
  { nombre: 'Sentadilla con barra', patron: 'Cadena Anterior 2P' },
  { nombre: 'Puente de gluteo isometrico', patron: 'Accesorios MMII' },
  { nombre: 'Empuje de Cadera con Barra', patron: 'Cadena Posterior 2P' },
  { nombre: 'Press con mancuernas en puente', patron: 'Accesorios MMSS' },
  { nombre: 'Press unilateral en puente', patron: 'Accesorios MMII' },
  { nombre: 'Peso muerto rumano sumo', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso muerto rumano asimetrico con mancuernas', patron: 'Cadena Posterior 1P' },
  { nombre: 'Press plano unilateral', patron: 'Empuje Horizontal 1P' },
  { nombre: 'Peso Muerto Rumano con Mancuernas', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso Muerto Rumano con deficit', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso Muerto bulgaro', patron: 'Cadena Posterior 1P' },
  { nombre: 'Sentadilla bulgara con deficit', patron: 'Cadena Anterior 1P' },
  { nombre: 'Buenos Días con Barra', patron: 'Cadena Posterior 2P' },
  { nombre: 'Sentadilla Búlgara', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla Búlgara con Salto', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla Split con mancuernas', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla de Copa', patron: 'Cadena Anterior 2P' },
  { nombre: 'Saltos al Cajón', patron: 'Saltos' },
  { nombre: 'Desaceleracion desde cajon', patron: 'Saltos' },
  { nombre: 'Salto contra movimiento desde cajon', patron: 'Saltos' },
  { nombre: 'Subida al cajon unipodal', patron: 'Accesorios MMII' },
  { nombre: 'Desaceleracion con cambio de direccion', patron: 'Saltos' },
  { nombre: 'Salto a cajon unipodal', patron: 'Saltos' },
  { nombre: 'Empuje de Cadera con Banda Redonda', patron: 'Cadena Posterior 2P' },
  { nombre: 'Salto contramovimiento a cajon', patron: 'Saltos' },
  { nombre: 'Desaceleracion desde cajon mas salto', patron: 'Saltos' },
  { nombre: 'Empuje de cadera unipodal con pelota', patron: 'Cadena Posterior 1P' },
  { nombre: 'Salto desde cajon enfasis vertical', patron: 'Saltos' },
  { nombre: 'Salto en valla mas salto a cajon', patron: 'Saltos' },
  { nombre: 'Empuje de Cadera Elevado Unipodal', patron: 'Cadena Posterior 1P' },
  { nombre: 'Salto MB mas vallas mas salto a cajon', patron: 'Saltos' },
  { nombre: 'Salto en valla unipodal', patron: 'Saltos' },
  { nombre: 'Salto lateral', patron: 'Saltos' },
  { nombre: 'Salto bipodal', patron: 'Saltos' },
  { nombre: 'Salto lateral unipodal en conos', patron: 'Saltos' },
  { nombre: 'Plancha lateral mas elevacion', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Rock back de aductores', patron: 'Movilidad' },
  { nombre: 'Sentadilla Búlgara con Déficit', patron: 'Cadena Anterior 1P' },
  { nombre: 'ISO push BB flor press', patron: 'Isometrico' },
  { nombre: 'Press pallof vertical', patron: 'Anti-Extension' },
  { nombre: 'Press pallof a bisagra', patron: 'Anti-Rotacion' },
  { nombre: 'Sentadilla de Pulso A', patron: 'Cadena Anterior 2P' },
  { nombre: 'Step Down', patron: 'Accesorios MMII' },
  { nombre: 'Subidas al cajon con carga', patron: 'Accesorios MMII' },
  { nombre: 'Estocada atras', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla tempo 5 3 1', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla frontal', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla zombie', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla Skater', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla Cosaco con Trapo', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla de Zercher', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla superman', patron: 'Cadena Anterior 2P' },
  { nombre: 'Good morning zercher', patron: 'Cadena Posterior 2P' },
  { nombre: 'Estocada atras zercher', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla con disco', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla a Cajón (Box squat)', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla de Arranque', patron: 'Cadena Anterior 2P' },
  { nombre: 'Estocada caminando', patron: 'Cadena Anterior 1P' },
  { nombre: 'Press Militar con Barra', patron: 'Empuje Vertical 2B' },
  { nombre: 'Thruster con mancuernas', patron: 'Empuje Vertical 2B' },
  { nombre: 'Press Militar con Mancuernas', patron: 'Empuje Vertical 2B' },
  { nombre: 'Press Plano (Bench press)', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Flexiones de brazos regresion', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Flexiones de brazos en paralelas', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Flexiones de brazos', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Flexiones de brazos Inclinadas', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Flexiones de brazos Declinadas', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Curl nordico invertido mas press', patron: 'Accesorios MMII' },
  { nombre: 'Curl nordico invertido', patron: 'Accesorios MMII' },
  { nombre: 'Press javalina', patron: 'Empuje Vertical 1B' },
  { nombre: 'Cargada de potencia a cajon', patron: 'DLP' },
  { nombre: 'Aperturas con Mancuernas disociadas', patron: 'Accesorios MMSS' },
  { nombre: 'Fondos en banco', patron: 'Accesorios MMSS' },
  { nombre: 'Rotaciones toracicas en cuadrupedia', patron: 'Movilidad' },
  { nombre: 'Rotaciones toraco dorsal semi arrodillado', patron: 'Movilidad' },
  { nombre: 'Rotaciones toracicas en bisagra', patron: 'Movilidad' },
  { nombre: 'Rotaciones toracicas sobre rodillas', patron: 'Movilidad' },
  { nombre: 'Movilidad dorsal en cuadrupedia', patron: 'Movilidad' },
  { nombre: 'Aperturas con Mancuernas', patron: 'Accesorios MMSS' },
  { nombre: 'Remo a 1 brazo', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Dominadas supinas', patron: 'Traccion Vertical 2B' },
  { nombre: 'Remo invertido 45°', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo prono en TRX', patron: 'Traccion Vertical 2B' },
  { nombre: 'Remo neutro en Trx', patron: 'Traccion Vertical 2B' },
  { nombre: 'Remo supino', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Gato bueno Gato malo', patron: 'Movilidad' },
  { nombre: 'Remo con Barra', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Movilidad escapular', patron: 'Movilidad' },
  { nombre: 'Movilidad dinamica de psoas', patron: 'Movilidad' },
  { nombre: 'Movilidad dinamica de isquio', patron: 'Movilidad' },
  { nombre: 'Remo Horizontal con Mancuernas', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo neutro en TRX sobre cajon', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Movilidad de isquio/cadera', patron: 'Movilidad' },
  { nombre: 'Flexion extension de rodilla', patron: 'Movilidad' },
  { nombre: 'Movilidad de tobillo con carga', patron: 'Movilidad' },
  { nombre: 'Rueda abdominal', patron: 'Anti-Extension' },
  { nombre: 'Plancha abdominal alejada', patron: 'Anti-Extension' },
  { nombre: 'Bird dog avanzado', patron: 'Estabilidad Posterior' },
  { nombre: 'Peso muerto convencional', patron: 'Cadena Posterior 2P' },
  { nombre: 'Movilidad de tobillo con banda', patron: 'Movilidad' },
  { nombre: 'Plancha en Fitball', patron: 'Anti-Extension' },
  { nombre: 'RollOut en Fitball', patron: 'Anti-Extension' },
  { nombre: 'Revolver la Olla', patron: 'Anti-Extension' },
  { nombre: 'Plancha', patron: 'Anti-Extension' },
  { nombre: 'Plancha con rotacion', patron: 'Anti-Extension' },
  { nombre: 'Bird Dog', patron: 'Anti-Flexion' },
  { nombre: 'Plancha Lateral con Rodilla Apoyada', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Hollow', patron: 'Anti-Extension' },
  { nombre: 'Empuje de cadera', patron: 'Cadena Posterior 2P' },
  { nombre: 'Plancha Lateral Glúteo Medio', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Partida desde banco mas Salto con rotacion a cajon', patron: 'Saltos' },
  { nombre: 'TB tiron alto', patron: 'DLP' },
  { nombre: 'Press Pallof TB', patron: 'Anti-Rotacion' },
  { nombre: 'Press Pallof con carga', patron: 'Anti-Rotacion' },
  { nombre: 'Salto al cajón rotacional sentado', patron: 'Saltos' },
  { nombre: 'Salto al cajon Desde sentado', patron: 'Saltos' },
  { nombre: 'CM horizontal box jump', patron: 'Saltos' },
  { nombre: 'CM rotacional box jump', patron: 'Saltos' },
  { nombre: 'Bicho muerto 3 1', patron: 'Anti-Extension' },
  { nombre: 'Bicho muerto doble', patron: 'Anti-Extension' },
  { nombre: 'Bicho muerto', patron: 'Anti-Extension' },
  { nombre: 'Flexion de brazos reactivo', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Arm kb', patron: 'Movilidad' },
  { nombre: 'Plancha en fitball con impulso', patron: 'Anti-Extension' },
  { nombre: 'Plancha con los codos extendidos', patron: 'Anti-Extension' },
  { nombre: 'Halo', patron: 'CORE' },
  { nombre: 'Halo en cuclillas', patron: 'CORE' },
  { nombre: 'ISO push BB 1 leg squat', patron: 'Isometrico' },
  { nombre: 'Plancha Lateral Copenhague', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Dragon Flag excéntrico', patron: 'CORE' },
  { nombre: '2P CCM vertical asistido', patron: 'Saltos' },
  { nombre: '2P vertical CC reactivo', patron: 'Saltos' },
  { nombre: 'Press pallof (anti extensión a anti lateral)', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof en estocada', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Estocada atras con mancuerna', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla frontal con elevacion de talon', patron: 'Cadena Anterior 2P' },
  { nombre: 'Elevacion en plancha lateral', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Patada lateral gluteo', patron: 'Accesorios MMII' },
  { nombre: 'Posicion de sentadilla', patron: 'Movilidad' },
  { nombre: '8 kb', patron: 'CORE' },
  { nombre: 'Estiramiento dinamico cadena posterior', patron: 'Movilidad' },
  { nombre: 'Marcha de granjero unilateral', patron: 'Transporte' },
  { nombre: 'Marcha de granjero', patron: 'Transporte' },
  { nombre: 'Arranque dinamico con mancuerna', patron: 'DLP' },
  { nombre: 'Arranque con mancuerna', patron: 'DLP' },
  { nombre: 'Estocada isometrica sobre disco', patron: 'Isometrico' },
  { nombre: 'Estocada isometrica talon elevado', patron: 'Isometrico' },
  { nombre: 'Rotaciones toracias 90-90', patron: 'Movilidad' },
  { nombre: 'Remo en ladmine', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Estiramiento de gluteo', patron: 'Movilidad' },
  { nombre: 'Curl de biceps en trx', patron: 'Accesorios MMSS' },
  { nombre: 'Seal jack', patron: 'Peso Corporal' },
  { nombre: 'Frog Pump', patron: 'Peso Corporal' },
  { nombre: 'Sentadilla a 1 pierna a cajon', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla a 1 pierna pistol', patron: 'Cadena Anterior 1P' },
  { nombre: 'Movilidad de isquio con banda', patron: 'Movilidad' },
  { nombre: 'Abduccion con banda', patron: 'Banda' },
  { nombre: 'Pull Apart', patron: 'Movilidad' },
  { nombre: 'Regresion de peso muerto a 1 pierna', patron: 'Cadena Posterior 1P' },
  { nombre: 'Peso muerto unipodal kb', patron: 'Cadena Posterior 1P' },
  { nombre: 'Mountain climbers', patron: 'Peso Corporal' },
  { nombre: 'Mountain climbers semi circle', patron: 'Peso Corporal' },
  { nombre: 'In and out', patron: 'Peso Corporal' },
  { nombre: 'Bisagra de Cadera con Bastón', patron: 'Cadena Posterior 2P' },
  { nombre: 'Plancha jack', patron: 'Peso Corporal' },
  { nombre: 'Plancha con rotacion lateral', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Clean and jerk ladmine', patron: 'DLP' },
  { nombre: 'Arranque en ladmine', patron: 'DLP' },
  { nombre: 'Peso muerto en ladmine', patron: 'Cadena Posterior 1P' },
  { nombre: 'Remo en ladmine toma vikinga', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Sentadilla en ladmine', patron: 'Cadena Anterior 2P' },
  { nombre: 'Press vikingo', patron: 'Empuje Vertical 2B' },
  { nombre: 'Empuje de cadera con Abducción', patron: 'Cadena Posterior 2P' },
  { nombre: 'Press pallof en estocada rotacion', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof mas skipping', patron: 'Anti-Rotacion' },
  { nombre: 'Bisagra de cadera en fitball', patron: 'Anti-Extension' },
  { nombre: 'Regresion peso muerto unipodal', patron: 'Cadena Posterior 1P' },
  { nombre: 'Regresion peso muerto unipodal con band', patron: 'Cadena Posterior 1P' },
  { nombre: 'Movilidad activa de isquio', patron: 'Movilidad' },
  { nombre: 'Estocada caminando enfoque en gluteo', patron: 'Cadena Anterior 1P' },
  { nombre: 'Push press', patron: 'DLP' },
  { nombre: 'Tall clean', patron: 'DLP' },
  { nombre: 'Lateral hop', patron: 'Saltos' },
  { nombre: 'Skater jump al cajon', patron: 'Saltos' },
  { nombre: 'Tall power jerk', patron: 'DLP' },
  { nombre: 'Movilidad de hombros en MB', patron: 'Movilidad' },
  { nombre: 'Preventivo de espalda', patron: 'Preventivos' },
  { nombre: 'Movilidad de cadera 90/90', patron: 'Movilidad' },
  { nombre: 'Salto con banda de resistencia', patron: 'Saltos' },
  { nombre: 'Salto lateral + salto al cajon', patron: 'Saltos' },
  { nombre: 'Split jump + salto al cajon', patron: 'Saltos' },
  { nombre: 'Dominadas a un brazo', patron: 'Traccion Vertical 2B' },
  { nombre: 'Seal row', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Core en puente', patron: 'CORE' },
  { nombre: 'Dominadas prono', patron: 'Traccion Vertical 2B' },
  { nombre: 'Dominadas tras nuca', patron: 'Traccion Vertical 2B' },
  { nombre: 'Dragon flag leg', patron: 'CORE' },
  { nombre: 'Dragon flag truck', patron: 'CORE' },
  { nombre: 'Dragon flag negative', patron: 'CORE' },
  { nombre: 'Dragon flag pulso', patron: 'CORE' },
  { nombre: 'Swing T handle', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso muerto toma de arranque', patron: 'Cadena Posterior 2P' },
  { nombre: 'Stradle lift', patron: 'Accesorios MMII' },
  { nombre: 'Aperturas de pecho en TRX', patron: 'Accesorios MMSS' },
  { nombre: 'Press pecho en TRX', patron: 'Accesorios MMSS' },
  { nombre: 'Press frances en TRX', patron: 'Accesorios MMSS' },
  { nombre: 'Curl femoral en TRX', patron: 'Accesorios MMII' },
  { nombre: 'Plancha dinamica supina', patron: 'Anti-Extension' },
  { nombre: 'Plancha supina', patron: 'Anti-Extension' },
  { nombre: 'Plancha alta supina', patron: 'Anti-Extension' },
  { nombre: 'Plancha baja supina', patron: 'Anti-Extension' },
  { nombre: 'Press de banco con mancuernas', patron: 'Accesorios MMSS' },
  { nombre: 'Empuje de cadera a una pierna mas press', patron: 'Accesorios MMSS' },
  { nombre: 'Empuje de cadera mas press', patron: 'Accesorios MMSS' },
  { nombre: 'Press z dumbell', patron: 'Empuje Vertical 2B' },
  { nombre: 'Plancha quito apoyos', patron: 'Anti-Extension' },
  { nombre: 'Plancha toque de hombros', patron: 'Anti-Extension' },
  { nombre: 'Plancha mas empuje', patron: 'Anti-Extension' },
  { nombre: 'Plancha lateral + remo', patron: 'Anti-Extension' },
  { nombre: 'Plancha alta + traslado', patron: 'Anti-Extension' },
  { nombre: 'Plancha posicion de oso + traslado', patron: 'Anti-Extension' },
  { nombre: 'Swing de la cabra kb', patron: 'Cadena Posterior 2P' },
  { nombre: 'Vuelos frontal con disco', patron: 'Accesorios MMSS' },
  { nombre: 'Vuelos frontales con mancuerna', patron: 'Accesorios MMSS' },
  { nombre: 'Vuelos laterales', patron: 'Accesorios MMSS' },
  { nombre: 'Plancha lateral gluteo medio', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Fondos en banco regresion', patron: 'Accesorios MMSS' },
  { nombre: 'Larseen press', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Frog pump', patron: 'Accesorios MMII' },
  { nombre: 'Elevacion de cadera elevado kb', patron: 'Cadena Posterior 2P' },
  { nombre: 'Elevacion de cadera unipodal elevado', patron: 'Cadena Posterior 1P' },
  { nombre: 'Empuje de cadera con banda', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso muerto piernas rigidas', patron: 'Cadena Posterior 2P' },
  { nombre: 'Cargada de potencia colgado', patron: 'DLP' },
  { nombre: 'Envion de potencia', patron: 'DLP' },
  { nombre: 'Salto vertical con banda de resistencia', patron: 'Saltos' },
  { nombre: 'Movilidad dinamica de isquio en un apoyo', patron: 'Movilidad' },
  { nombre: 'Plancha copenhague', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Plancha copenhague regresion', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Camino a la plancha', patron: 'Anti-Extension' },
  { nombre: 'Plancha lateral aductor', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Masaje foam roll aductor', patron: 'Liberacion Miofascial' },
  { nombre: 'Masaje foam roll tensor de la fascia', patron: 'Liberacion Miofascial' },
  { nombre: 'Masaje foam roll isquio', patron: 'Liberacion Miofascial' },
  { nombre: 'Bicho muerto con disco', patron: 'Anti-Extension' },
  { nombre: 'Bicho muriendo con disco', patron: 'Anti-Extension' },
  { nombre: 'Gemelos con barra', patron: 'Accesorios MMII' },
  { nombre: 'Patron respiratorio posicion bebe', patron: 'Respiratorio' },
  { nombre: 'Patron respiratorio progresion', patron: 'Respiratorio' },
  { nombre: 'Patron respiratorio acostado', patron: 'Respiratorio' },
  { nombre: 'Bisagra de cadera', patron: 'Cadena Posterior 2P' },
  { nombre: 'Hiperextension de cadera prono', patron: 'Accesorios MMII' },
  { nombre: 'Puente bilateral con tension', patron: 'Accesorios MMII' },
  { nombre: 'Remo en dos apoyos', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Remo invertido a 45 supino', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo prono regresion (chin up)', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Remo invertido prono (chin up)', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo invertido sobre cajon', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo con banda unilateral', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Curl de biceps alternados', patron: 'Accesorios MMSS' },
  { nombre: 'Curl de biceps martillo', patron: 'Accesorios MMSS' },
  { nombre: 'Remo con barra toma prono', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Remo con barra toma supina', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Curl de biceps con barra', patron: 'Accesorios MMSS' },
  { nombre: 'Acoples paralelos', patron: 'Anti-Extension' },
  { nombre: 'Curl de isquio excentrico', patron: 'Accesorios MMII' },
  { nombre: 'Levantada turca con kb', patron: 'CORE' },
  { nombre: 'Hike pass mas swing', patron: 'Cadena Posterior 2P' },
  { nombre: 'Hike pass kb', patron: 'Cadena Posterior 2P' },
  { nombre: 'BK clean pause', patron: 'DLP' },
  { nombre: 'Cat cow', patron: 'Movilidad' },
  { nombre: 'Impulso mas salto al cajon', patron: 'Saltos' },
  { nombre: 'Seal row peso corporal', patron: 'Peso Corporal' },
  { nombre: 'Recepcion lateral mas salto', patron: 'Saltos' },
  { nombre: 'Salto a una pierna', patron: 'Saltos' },
  { nombre: 'Clean con kb', patron: 'DLP' },
  { nombre: 'Swing frontal', patron: 'Cadena Posterior 2P' },
  { nombre: 'Patrones rotacionales kb', patron: 'CORE' },
  { nombre: 'Progresion roll out', patron: 'Anti-Extension' },
  { nombre: 'Roll out declinado', patron: 'Anti-Extension' },
  { nombre: 'Roll out con fitball', patron: 'Anti-Extension' },
  { nombre: 'Tgu con mancuerna', patron: 'CORE' },
  { nombre: 'Movilidad de tobillo sobre cajon', patron: 'Movilidad' },
  { nombre: 'Molino alto', patron: 'CORE' },
  { nombre: 'Molino completo', patron: 'CORE' },
  { nombre: 'Salto con carga', patron: 'Saltos' },
  { nombre: 'Lanzamiento MB Horizontal', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento frontal arrodillado MB', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento rotacional MB', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento bisagras MB', patron: 'Lanzamientos' },
  { nombre: 'Halo mas bisagras con disco', patron: 'CORE' },
  { nombre: 'Movilidad de hombros con banda', patron: 'Movilidad' },
  { nombre: 'Giros rusos', patron: 'CORE' },
  { nombre: 'Abdominales con carga', patron: 'CORE' },
  { nombre: 'Hollow dinamico', patron: 'Anti-Extension' },
  { nombre: 'Remo a un brazo pelvis alineada', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Remo a un brazo sobre banco', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Press militar posicion de caballero', patron: 'Empuje Vertical 2B' },
  { nombre: 'Press militar posicion dividida', patron: 'Empuje Vertical 2B' },
  { nombre: 'Press militar alternado', patron: 'Empuje Vertical 1B' },
  { nombre: 'Extension isometrica en banco rumano', patron: 'Isometrico' },
  { nombre: 'Cars de cadera', patron: 'Movilidad' },
  { nombre: 'Sentadilla isometrica a una pierna', patron: 'Isometrico' },
  { nombre: 'Sentadilla isometrica', patron: 'Isometrico' },
  { nombre: 'Plancha prona en 3 apoyos', patron: 'Anti-Extension' },
  { nombre: 'Cars de tobillo', patron: 'Movilidad' },
  { nombre: 'Cars de columna', patron: 'Movilidad' },
  { nombre: 'Sentadilla frontal asimetrica', patron: 'Cadena Anterior 1P' },
  { nombre: 'Remo pendlay', patron: 'Traccion Horizontal 2B' },
  { nombre: 'Estocadas con barra', patron: 'Cadena Anterior 1P' },
  { nombre: 'Curl de biceps con barra EZ', patron: 'Accesorios MMSS' },
  { nombre: 'Subidas al cajon a una pierna', patron: 'Cadena Anterior 1P' },
  { nombre: 'Marcha granjero zercher', patron: 'CORE' },
  { nombre: 'Flexion extension de tobillo', patron: 'Movilidad' },
  { nombre: 'Rotacion interna de tobillo', patron: 'Movilidad' },
  { nombre: 'Gato contento-enojado de tobillo', patron: 'Movilidad' },
  { nombre: 'Rotacion externa de hombro', patron: 'Movilidad' },
  { nombre: 'Face pull', patron: 'Movilidad' },
  { nombre: 'Liberacion miofascial plantar', patron: 'Liberacion Miofascial' },
  { nombre: 'Press unilateral', patron: 'Empuje Vertical 1B' },
  { nombre: 'Spiderman Alto', patron: 'Movilidad' },
  { nombre: 'Rotacion Toracica Foam roll', patron: 'Movilidad' },
  { nombre: 'Rotacion Toracica Con baston', patron: 'Movilidad' },
  { nombre: 'Cars de Hombros', patron: 'Movilidad' },
  { nombre: 'Push up + TH', patron: 'Anti-Extension' },
  { nombre: 'Peso muerto Asimetrico', patron: 'Cadena Posterior 1P' },
  { nombre: 'Triceps en Polea', patron: 'Accesorios MMSS' },
  { nombre: 'Rotaciones en Polea', patron: 'CORE' },
  { nombre: 'Press pallof antiextension', patron: 'Anti-Extension' },
  { nombre: 'Salto Horizontal Caida unipodal', patron: 'Saltos' },
  { nombre: 'Estocada ISO Catch', patron: 'Iso Catch' },
  { nombre: 'Power jerk', patron: 'DLP' },
  { nombre: 'Remo a un brazo Ladmine', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Glúteos isquiotibiales sobre banco', patron: 'Cadena Posterior 1P' },
  { nombre: 'Dominadas pliometricas', patron: 'Traccion Vertical 1B' },
  { nombre: 'Rotaciones con disco sobre Fitball', patron: 'CORE' },
  { nombre: 'Empuje de cadera asimetrico', patron: 'Cadena Posterior 1P' },
  { nombre: 'CMJ Arms Free', patron: 'Saltos' },
  { nombre: 'Salto SPLIT', patron: 'Saltos' },
  { nombre: 'Salto rotacional al cajon', patron: 'Saltos' },
  { nombre: 'Primer paso mas Salto al cajon', patron: 'Saltos' },
  { nombre: 'Saltos de aproximacion', patron: 'Saltos' },
  { nombre: 'Salto caida unipodal', patron: 'Saltos' },
  { nombre: 'De Rodilla mas salto', patron: 'Saltos' },
  { nombre: 'Salto en profundidad', patron: 'Saltos' },
  { nombre: 'Salto escalonado al cajon', patron: 'Saltos' },
  { nombre: 'Salto lateral hacia el soporte', patron: 'Saltos' },
  { nombre: 'Dominadas toma prona + lanz de MB sobre cabeza', patron: 'Traccion Vertical 2B' },
  { nombre: 'Press de banca + lanz de MB', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Press de banca + ext de BB con impulso', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Subidas al banco + subidas reactiva con salto', patron: 'Rodilla Dominante 1P' },
  { nombre: 'Peso muerto rumano 1P + peso muerto MB 1P + lanz', patron: 'Cadera Dominante 1P' },
  { nombre: 'Sentadilla bulgara con barra + sentadilla bulgara con salto', patron: 'Rodilla Dominante 1P' },
  { nombre: 'Estocada lateral con barra + bound', patron: 'Rodilla Dominante 1P' },
  { nombre: 'Sentadilla + press de H + lanz vertical de MB', patron: 'Rodilla Dominante 2P' },
  { nombre: 'Empuje de fuerza con barra + saltar y alcanzar', patron: 'Rodilla Dominante 2P' },
  { nombre: 'Lanzamiento al piso desde cabeza con MB 2B', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento laterales al piso desde cabeza con MB 2B', patron: 'Lanzamientos' },
  { nombre: 'Lanzamientos laterales al piso desde cabeza con MB 2B sentado', patron: 'Lanzamientos' },
  { nombre: 'Sentadilla + lanzamientos hacia arriba por encima de cabeza', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de pecho con MB en posicion supina', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de pecho con MB arrodillado alt', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de pecho con MB + extension de cadera', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento a 1B con MB arrodillado alterno', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento a 1B con MB parado alterno', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de pecho con MB de pie', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento a 1B con MB arrodillado', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de pecho con MB arrodillado desde posicion elevada', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento rotatorio con MB de pie', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento lateral con MB arrodillado alterno', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento por encima de la cabeza con MB en posicion supina sobre FB', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento lateral con MB arrodillado', patron: 'Lanzamientos' },
  { nombre: 'Posicion partida alta + lanzamiento de pecho con MB', patron: 'Lanzamientos' },
  { nombre: 'Aceleracion + lanzamiento de pecho con MB', patron: 'Lanzamientos' },
  { nombre: 'Desplazamiento lateral + freno + cambio de direccion + lanz de MB', patron: 'Lanzamientos' },
  { nombre: 'Peso muerto rumano a 1P + lanz MB', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de arriba a bajo arrodillado alterno', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento de arriba a bajo parado alterno', patron: 'Lanzamientos' },
  { nombre: 'Peso muerto a 1P con caida de MB', patron: 'Cadera Dominante 1P' },
  { nombre: 'Lanzamiento hacia el piso desde cabeza arrodillado', patron: 'Lanzamientos' },
  { nombre: 'Sentadilla con barra + salto sobre box', patron: 'Rodilla Dominante 2P' },
  { nombre: 'Sentadilla en maquina Smith', patron: 'Cadena Anterior 2P' },
  { nombre: 'Sentadilla Split en maquina Smith', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara en maquina Smith', patron: 'Cadena Anterior 1P' },
  { nombre: 'Press de banca en maquina Smith', patron: 'Empuje Horizontal 2B' },
  { nombre: 'Aperturas en polea', patron: 'Accesorios MMSS' },
  { nombre: 'Remo de pie en polea 1B', patron: 'Traccion Vertical 1B' },
  { nombre: 'Dorsales en maquina prono', patron: 'Traccion Vertical 2B' },
  { nombre: 'Dorsales en polea supino', patron: 'Traccion Vertical 2B' },
  { nombre: 'Extensiones laterales en polea', patron: 'Accesorios MMSS' },
  { nombre: 'Vuelo lateral en polea', patron: 'Accesorios MMSS' },
  { nombre: 'Curl de biceps en polea', patron: 'Accesorios MMSS' },
  { nombre: 'Curl de isquio en maquina', patron: 'Accesorios MMII' },
  { nombre: 'Curl de isquio en maquina 2-1', patron: 'Accesorios MMII' },
  { nombre: 'Press de pecho en maquina (peck deck)', patron: 'Accesorios MMSS' },
  { nombre: 'Cuadriceps en maquina', patron: 'Accesorios MMII' },
  { nombre: 'Cuadriceps en maquina + isometria en extension', patron: 'Accesorios MMII' },
  { nombre: 'Peck deck (Aperturas)', patron: 'Accesorios MMSS' },
  { nombre: 'Prensa horizontal 2P', patron: 'Accesorios MMII' },
  { nombre: 'Prensa a 45° 2P', patron: 'Accesorios MMII' },
  { nombre: 'Prensa a 45° 1P', patron: 'Accesorios MMII' },
  { nombre: 'Sentadilla con barra Iso catch', patron: 'Iso Catch' },
  { nombre: 'Puente de gluteos Iso Switch', patron: 'Iso Switch' },
  { nombre: 'Isquio en cajon Iso Catch', patron: 'Iso Catch' },
  { nombre: 'Puente de Gluteos Iso catch', patron: 'Iso Catch' },
  { nombre: 'Remo en TRX Iso Catch', patron: 'Iso Catch' },
  { nombre: 'Remo a un brazo en TRX Iso catch', patron: 'Iso Catch' },
  { nombre: 'Aterrisaje de un brazo iso catch', patron: 'Iso Catch' },
  { nombre: 'Flexion de brazos Iso catch', patron: 'Iso Catch' },
  { nombre: 'Caida de rodilla Iso catch', patron: 'Iso Catch' },
  { nombre: 'Flexion de brazos declinadas Iso catch', patron: 'Iso Catch' },
  { nombre: 'Lanzamiento mas drill', patron: 'Lanzamientos' },
  { nombre: 'Salto desde rodilla mas lanzamiento', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento horizontal', patron: 'Lanzamientos' },
  { nombre: 'Primer paso mas lanzamiento', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento 1 Brazo', patron: 'Lanzamientos' },
  { nombre: 'Lanzamiento patron rotacional', patron: 'Lanzamientos' },
  { nombre: 'Cars de cadera sobre rack', patron: 'Movilidad' },
  { nombre: 'Lanzamiento de bala en ladmine', patron: 'Lanzamientos' },
  { nombre: 'Rack chin plyo', patron: 'Accesorios MMSS' },
  { nombre: 'Pull up plyo', patron: 'Accesorios MMSS' },
  { nombre: 'Push up plyo sobre discos', patron: 'Accesorios MMSS' },
  { nombre: 'Push up plyo', patron: 'Accesorios MMSS' },
  { nombre: 'Push up plyo lateral', patron: 'Accesorios MMSS' },
  { nombre: 'RDL Iso catch', patron: 'Iso Catch' },
  { nombre: 'Sentadilla split Iso catch', patron: 'Iso Catch' },
  { nombre: 'Iso push desde tobillo', patron: 'Iso Push' },
  { nombre: 'Push up iso catch bodyweight', patron: 'Iso Catch' },
  { nombre: 'Remo 1b Iso catch', patron: 'Iso Catch' },
  { nombre: 'Sentadilla bulgara Iso catch', patron: 'Iso Catch' },
  { nombre: 'Estocada Iso catch', patron: 'Iso Catch' },
  { nombre: 'Una sola pierna Iso catch', patron: 'Iso Catch' },
  { nombre: 'Salto concentrico', patron: 'Saltos' },
  { nombre: 'Tuck jump', patron: 'Saltos' },
  { nombre: 'CMJ jump', patron: 'Saltos' },
  { nombre: 'CMJ squat jump', patron: 'Saltos' },
  { nombre: 'Drop Jump', patron: 'Saltos' },
  { nombre: 'Salto con caida a una pierna', patron: 'Saltos' },
  { nombre: 'Salto bipodal desde tobillo', patron: 'Saltos' },
  { nombre: 'Sentadilla bulgara con resistencia lateral', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara de arranque', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara pulso', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara goblet', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara OH 1b', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara sobre hombros', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara OH DB', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara OH con disco', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara contralateral', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara homolateral', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara 1b sobre hombro', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara apoyo metatarso', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara con deficit DB', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara antiflexion', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara con salto', patron: 'Cadena Anterior 1P' },
  { nombre: 'Sentadilla bulgara con disco', patron: 'Cadena Anterior 1P' },
  { nombre: 'Cargada de potencia', patron: 'DLP' },
  { nombre: 'Estocada Iso hold', patron: 'Iso Hold' },
  { nombre: 'Peso muerto unipodal con barra', patron: 'Cadena Posterior 1P' },
  { nombre: 'Vuelos posteriores DB', patron: 'Accesorios MMSS' },
  { nombre: 'Pull up con banda de resistencia', patron: 'Accesorios MMSS' },
  { nombre: 'Saltos bipodales con banda de resistencia', patron: 'Saltos' },
  { nombre: 'Press en ladmine posicion estocada', patron: 'Empuje Vertical 1B' },
  { nombre: 'Press ladmine apoyos asimetricos', patron: 'Empuje Vertical 1B' },
  { nombre: 'RDL en ladmine', patron: 'Cadena Posterior 2P' },
  { nombre: 'Peso muerto unipodal en ladmine', patron: 'Cadena Posterior 1P' },
  { nombre: 'Remo 1b en ladmine', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Drop Jump Caida Unipodal', patron: 'Saltos' },
  { nombre: 'Sentadilla Bulgara Excentrica acentuada', patron: 'Cadena Anterior 1P' },
  { nombre: 'Lanzamiento Horizontal Isquio Activo', patron: 'Lanzamientos' },
  { nombre: 'Press Militar de rodillas', patron: 'Empuje Vertical 2B' },
  { nombre: 'Plancha Frontal + Vuelo lateral', patron: 'Anti-Extension' },
  { nombre: 'Marcha Granjero Zercher', patron: 'Anti-Flexion' },
  { nombre: 'Press Pallof estocada', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof + paso de aceleracion', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof marcha', patron: 'Anti-Flexion' },
  { nombre: 'Press pallof apoyos asimetricos', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof de rodillas', patron: 'Anti-Rotacion' },
  { nombre: 'Press pallof + Skipping', patron: 'Anti-Rotacion' },
  { nombre: 'Estocada hacia atras + pallof', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Remo a un brazo + peso muerto unipodal Iso catch', patron: 'Iso Catch' },
  { nombre: 'Plancha alta dinamica con cambio de apoyos', patron: 'Anti-Extension' },
  { nombre: 'Press pallof Dinamico', patron: 'Anti-Flexion Lateral' },
  { nombre: 'Rotaciones en ladmine', patron: 'CORE' },
  { nombre: 'Remo a un brazo en puente TRX', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Plancha frontal + lateral', patron: 'Anti-Extension' },
  { nombre: 'Marcha Granjero + Press', patron: 'CORE' },
  { nombre: 'Marcha Granjero Con mancuernas', patron: 'CORE' },
  { nombre: 'Acoples paralelos o cruzados', patron: 'Anti-Extension' },
  { nombre: 'Arranque Frances', patron: 'DLP' },
  { nombre: 'Cargada Frances', patron: 'DLP' },
  { nombre: 'Segundo tiempo tijera', patron: 'DLP' },
  { nombre: 'Segundo tiempo tijera trasnuca', patron: 'DLP' },
  { nombre: 'Remo a 1 Brazo en cuadrupedia', patron: 'Traccion Horizontal 1B' },
  { nombre: 'Catch Unipodal', patron: 'Saltos' },
  { nombre: 'Press en Banco plano unilateral', patron: 'Empuje Horizontal 1B' },
  { nombre: 'Estocada lateral en ladmine', patron: 'Cadena Anterior 1P' },
  { nombre: 'Salto lateral en vallas', patron: 'Saltos' },
  { nombre: 'Primer paso + Salto a cajón', patron: 'Saltos' },
  { nombre: 'Saltos Reactivos a cajón', patron: 'Saltos' },
  { nombre: 'Drop jump a Cajon', patron: 'Saltos' },
  { nombre: 'Drop Jump + Salto horizontal + Salto en diagonal', patron: 'Saltos' },
  { nombre: 'Saltos horizontal reactivo', patron: 'Saltos' },
  { nombre: 'Drop jump + Salto horizontal', patron: 'Saltos' },
  { nombre: 'Bounds alternos', patron: 'Saltos' },
  { nombre: 'Hops en desplazamiento', patron: 'Saltos' },
  { nombre: 'Salto bipodal + Salto en Altura', patron: 'Saltos' },
  { nombre: 'Locomotive plyometric', patron: 'Saltos' },
  { nombre: 'Tobillo iso push', patron: 'Accesorios MMII' },
  { nombre: 'Sprint 10 Metros', patron: 'Sprint' },
  { nombre: 'Peso muerto ISO push', patron: 'Iso Push' },
];

async function main() {
  console.log(`Insertando ${ejercicios.length} ejercicios...`);
  const result = await prisma.ejercicio.createMany({
    data: ejercicios.map(e => ({ nombre: e.nombre, patron: e.patron, activo: true })),
    skipDuplicates: true,
  });
  console.log(`✓ ${result.count} ejercicios insertados.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());