// Script para poblar videoUrl en ejercicios existentes
// Ejecutar: node scripts/seed-videos.mjs

import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';
import * as dotenv from 'dotenv';
dotenv.config();

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// [nombre sin categoría, url limpio]
const VIDEOS = [
  ['Peso Muerto Sumo convencional', 'https://www.youtube.com/watch?v=zHOQxzuKkZU'],
  ['Peso Muerto Rumano', 'https://www.youtube.com/watch?v=9tSjo0tmJWs'],
  ['Peso Muerto con Trap Bar', 'https://www.youtube.com/watch?v=EFURI3CUwwc'],
  ['Peso muerto rumano asimetrico', 'https://www.youtube.com/watch?v=eXgkW5aBufQ'],
  ['Patada de gluteos', 'https://www.youtube.com/shorts/7o679wVypZ8'],
  ['Elevacion de cadera en fitball', 'https://www.youtube.com/watch?v=T7jtHVirLsU'],
  ['Elevacion de cadera', 'https://www.youtube.com/watch?v=qCsqXH9r8Y4'],
  ['Elevacion de Cadera a una pierna', 'https://www.youtube.com/watch?v=yYmdcjtp6dA'],
  ['Caminatas de Isquios', 'https://www.youtube.com/watch?v=8frk7SgdfSQ'],
  ['Curl de Isquio en Fitball', 'https://www.youtube.com/watch?v=r1mpa9MzhbA'],
  ['Empuje de Cadera Elevado', 'https://www.youtube.com/watch?v=HJ3tIu6jTqI'],
  ['Peso Muerto con Kettlebell', 'https://www.youtube.com/watch?v=tzuNvfqTCzM'],
  ['Swing con Kettlebell', 'https://youtu.be/e_dclMWOUkU'],
  ['Swing con kettlebell a un brazo', 'https://youtu.be/XMgRbJ2FLC0'],
  ['Saltos horizontales', 'https://www.youtube.com/watch?v=I90IazvXpKY'],
  ['Saltos desde Rodillas', 'https://www.youtube.com/shorts/XQXVDoKeVLA'],
  ['Peso Muerto Unipodal', 'https://www.youtube.com/watch?v=05zVWa3JjMg'],
  ['Sentadilla con barra', 'https://www.youtube.com/shorts/fEFRpEt92MY'],
  ['Puente de gluteo isometrico', 'https://www.youtube.com/watch?v=a6xV7Dm35Eo'],
  ['Empuje de Cadera con Barra', 'https://www.youtube.com/watch?v=vcfhPJXIHx0'],
  ['Press con mancuernas en puente', 'https://www.youtube.com/watch?v=cIK0kvgeo9E'],
  ['press unilateral en puente', 'https://www.youtube.com/watch?v=Js65dfI56wk'],
  ['Peso muerto rumano sumo', 'https://www.youtube.com/watch?v=9cxuJgnVgAY'],
  ['peso muerto rumano asimetrico con mancuernas', 'https://www.youtube.com/watch?v=7RH9I-5tjvc'],
  ['Press plano unilateral', 'https://www.youtube.com/watch?v=p1byDkOxkN8'],
  ['Peso Muerto Rumano con Mancuernas', 'https://www.youtube.com/watch?v=TSEY-DY4HHI'],
  ['Peso Muerto Rumano con con deficit', 'https://www.youtube.com/watch?v=k_OkQArkxvE'],
  ['Peso Muerto bulgaro', 'https://www.youtube.com/watch?v=yp4BhLIWqIg'],
  ['Sentadilla bulgara con deficit', 'https://www.youtube.com/watch?v=8PFgGuOdIm8'],
  ['Buenos Días con Barra', 'https://youtu.be/r83JrdAc6qc'],
  ['Sentadilla Búlgara', 'https://youtu.be/CIOSvXPyNog'],
  ['Sentadilla Búlgara con Salto', 'https://youtu.be/pvKPWzlbbJo'],
  ['Sentadilla Split con mancuernas', 'https://www.youtube.com/watch?v=17JzwPtKVPc'],
  ['Sentadilla de Copa', 'https://youtu.be/Q3C2fowGgRU'],
  ['Saltos al Cajón', 'https://www.youtube.com/watch?v=ljNEo9X4OZA'],
  ['Desaceleracion desde cajon', 'https://www.youtube.com/watch?v=qd_B779zjqE'],
  ['Salto contra movimiento desde cajon', 'https://www.youtube.com/watch?v=o_CMsTbn2n0'],
  ['Subida al cajon unipodal', 'https://www.youtube.com/watch?v=FXdUx8LECVc'],
  ['Desaceleracion con cambio de direccion', 'https://www.youtube.com/watch?v=L7YSUxW-tOo'],
  ['Salto a cajon unipodal', 'https://www.youtube.com/watch?v=vvpv3lQRPo0'],
  ['Empuje de Cadera con Banda Redonda', 'https://youtube.com/shorts/7k7lFs_icwg'],
  ['Salto contramovimiento a cajon', 'https://www.youtube.com/watch?v=xVwkMUBjrYE'],
  ['Desaceleracion desde cajon mas salto', 'https://www.youtube.com/watch?v=2XBplTBb904'],
  ['Empuje de cadera unipodal Con pelota', 'https://www.youtube.com/shorts/-4RIhwaAHAw'],
  ['Salto desde cajon enfasis vertical', 'https://www.youtube.com/watch?v=muwJiQJqjPE'],
  ['Salto en valla mas salto a cajon', 'https://www.youtube.com/watch?v=IXDSjlSV1C4'],
  ['Empuje de Cadera Elevado Unipodal', 'https://www.youtube.com/watch?v=G5BzqWfAxFk'],
  ['Salto MB mas vallas mas salto a cajon', 'https://www.youtube.com/watch?v=tvTybhvAvB4'],
  ['Salto en valla unipodal', 'https://www.youtube.com/watch?v=ol8f_0y5o78'],
  ['Salto lateral', 'https://www.youtube.com/watch?v=KVAD8aBPExc'],
  ['Salto bipodal', 'https://www.youtube.com/watch?v=7Fh_l1VBoZk'],
  ['Salto lateral unipodal en conos', 'https://www.youtube.com/watch?v=o490CFrJP9I'],
  ['Plancha lateral mas elevacion', 'https://www.youtube.com/watch?v=DHM4G5XOT7s'],
  ['rock back de aductores', 'https://www.youtube.com/watch?v=pxxPt_CTSD4'],
  ['Sentadilla Búlgara con Déficit', 'https://www.youtube.com/watch?v=8PFgGuOdIm8'],
  ['ISO push BB flor press', 'https://www.youtube.com/watch?v=2G5T5T0m3MA'],
  ['Press pallof vertical', 'https://www.youtube.com/watch?v=HjvueqmlAEk'],
  ['Press pallof a bisagra', 'https://www.youtube.com/watch?v=Mx21Qt-EFPc'],
  ['Sentadilla de Pulso A', 'https://www.youtube.com/watch?v=eJzbhjbI9ow'],
  ['Step Down', 'https://www.youtube.com/watch?v=Jx3PmgzQB94'],
  ['Subidas al cajon con carga', 'https://www.youtube.com/watch?v=hmJmLBEpUQw'],
  ['Estocada atras', 'https://www.youtube.com/watch?v=oFA1T7OvoSU'],
  ['Sentadilla tempo 5 3 1', 'https://www.youtube.com/shorts/b_3ke1gMETE'],
  ['Sentadilla frontal', 'https://www.youtube.com/shorts/Rc96FqWWFzk'],
  ['Sentadilla zombie', 'https://www.youtube.com/shorts/krbnO-EJ0lo'],
  ['Sentadilla Skater', 'https://www.youtube.com/shorts/wvUcsuXHzJY'],
  ['Sentadilla Cosaco con Trapo', 'https://www.youtube.com/watch?v=DEyYOc-KhVY'],
  ['Sentadilla de Zercher', 'https://www.youtube.com/shorts/llizYc6nCtA'],
  ['Sentadilla superman', 'https://www.youtube.com/shorts/vIW6GIwC7LE'],
  ['Good morning zercher', 'https://www.youtube.com/watch?v=FtfPhGRIFvc'],
  ['Estocada atras zercher', 'https://www.youtube.com/watch?v=8QG6OQdTEvg'],
  ['Sentadilla con disco', 'https://www.youtube.com/shorts/Wv9XWSQsiJU'],
  ['Sentadilla a Cajón', 'https://www.youtube.com/watch?v=f5fTirDUisI'],
  ['Sentadilla de Arranque', 'https://www.youtube.com/shorts/YKd_xW3P4ys'],
  ['Estocada caminando', 'https://www.youtube.com/watch?v=r1_xtv42-3I'],
  ['Press Militar con Barra', 'https://youtu.be/9yF7WQDyoiA'],
  ['Thruster con mancuernas', 'https://www.youtube.com/watch?v=cUWnt9X-qoY'],
  ['Press Militar con Mancuernas', 'https://www.youtube.com/watch?v=_HpB169aqcY'],
  ['Press Plano', 'https://www.youtube.com/watch?v=f3lTBzhJ134'],
  ['Flexiones de brazos regresion', 'https://www.youtube.com/watch?v=wpCCebqEn3M'],
  ['Flexiones de brazos en paralelas', 'https://www.youtube.com/watch?v=RNvv35kUsUk'],
  ['Flexiones de brazos', 'https://www.youtube.com/watch?v=TCVY-WL7keA'],
  ['Flexiones de brazos Inclinadas', 'https://www.youtube.com/watch?v=SPYtpn3XW0g'],
  ['Flexiones de brazos Declinadas', 'https://www.youtube.com/watch?v=Tg0w1aUr2X4'],
  ['Curl  nordico invertido mas press', 'https://www.youtube.com/watch?v=IP3d9WNcjO4'],
  ['Curl nordico invertido', 'https://www.youtube.com/watch?v=Eifq68P1_cI'],
  ['Press javalina', 'https://www.youtube.com/watch?v=eXHduxXNiQw'],
  ['Cargada de potencia a cajon', 'https://www.youtube.com/watch?v=qTLJcmAczdo'],
  ['Aperturas con Mancuernas disociadas', 'https://www.youtube.com/watch?v=HxDK6lQUMcA'],
  ['Fondos en banco', 'https://www.youtube.com/watch?v=666_vpJ5krM'],
  ['Rotaciones toracicas en cuadrupedia', 'https://www.youtube.com/watch?v=CLU3uubUfLU'],
  ['Rotaciones toraco dorsal semi arrodillado', 'https://www.youtube.com/watch?v=6bfA1MhY3Ko'],
  ['Rotaciones toracicas en bisagra', 'https://www.youtube.com/watch?v=B6Tuen-EW50'],
  ['Rotaciones toracicas sobre rodillas', 'https://www.youtube.com/watch?v=RjZHQa8wV_k'],
  ['Movilidad dorsal en cuadrupedia', 'https://www.youtube.com/watch?v=fLhzV1HiPp4'],
  ['Aperturas con Mancuernas', 'https://www.youtube.com/watch?v=5t6i8x8NawQ'],
  ['Remo a 1 brazo', 'https://www.youtube.com/watch?v=yf68FaeCvZc'],
  ['Dominadas supinas', 'https://www.youtube.com/watch?v=eIoCgZvXEMI'],
  ['Remo invertido 45°', 'https://www.youtube.com/watch?v=gvE0JcztjDA'],
  ['Remo prono en TRX', 'https://youtu.be/9jOA1wJkQFM'],
  ['Remo neutro en Trx', 'https://youtu.be/KEyUDtK4yhg'],
  ['Remo supino', 'https://youtu.be/WvbQvCyiad0'],
  ['Gato bueno Gato malo', 'https://www.youtube.com/watch?v=cpGUoCG9tHA'],
  ['Remo con Barra', 'https://www.youtube.com/watch?v=Ba_9X2DVDng'],
  ['Movilidad escapular', 'https://www.youtube.com/watch?v=_0Gjj4lhoUE'],
  ['Movilidad dinamica de psoas', 'https://www.youtube.com/watch?v=p0LmQK1_xHc'],
  ['Movilidad dinamica de isquio', 'https://www.youtube.com/watch?v=AZuWlDMmTHM'],
  ['Remo Horizontal con Mancuernas', 'https://www.youtube.com/watch?v=4hyDhWcPfR0'],
  ['Remo neutro en TRX sobre cajon', 'https://www.youtube.com/watch?v=09Hx6RSAAgM'],
  ['Movilidad de isquio/cadera', 'https://www.youtube.com/watch?v=y9uhMIlnhRI'],
  ['Flexion extension de rodilla', 'https://www.youtube.com/watch?v=Pk89kMt_xY0'],
  ['Movilidad de tobillo con carga', 'https://www.youtube.com/watch?v=Qbq2WP_IERo'],
  ['Rueda abdominal', 'https://www.youtube.com/watch?v=QfPvPBZCVGg'],
  ['Plancha abdominal alejada', 'https://www.youtube.com/shorts/Oz2VOj4vLmY'],
  ['Bird dog avanzado', 'https://www.youtube.com/shorts/awIrGS5jKqE'],
  ['Peso muerto convencional', 'https://www.youtube.com/watch?v=nDAaHT3QdMU'],
  ['Movilidad de tobillo con banda', 'https://www.youtube.com/watch?v=uwLiV59gvfQ'],
  ['Plancha en Fitball', 'https://www.youtube.com/watch?v=dAwY4SUgMts'],
  ['RollOut en Fitball', 'https://www.youtube.com/shorts/l7l8e6SyRTE'],
  ['Revolver la Olla', 'https://www.youtube.com/shorts/vWPj5S4ZHvg'],
  ['Plancha', 'https://www.youtube.com/shorts/EEipTaaxEnI'],
  ['Plancha con rotacion', 'https://www.youtube.com/shorts/ituGP9ZwPhw'],
  ['Bird Dog', 'https://www.youtube.com/shorts/TL263CyTluY'],
  ['Plancha Lateral con Rodilla Apoyada', 'https://www.youtube.com/shorts/AJbWvFKZV_8'],
  ['Hollow', 'https://www.youtube.com/watch?v=N5YhpGo7v7g'],
  ['Empuje de cadera', 'https://www.youtube.com/shorts/wLvfHxGI_i4'],
  ['Plancha Lateral Glúteo Medio', 'https://www.youtube.com/shorts/kZS_XTY-1Ww'],
  ['Partida desde banco mas Salto con rotacion a cajon', 'https://www.youtube.com/watch?v=BYffXP_7VGo'],
  ['TB tiron alto', 'https://www.youtube.com/watch?v=uT-8_wQAi2k'],
  ['Press Pallof TB', 'https://www.youtube.com/shorts/idsBhB-NbwU'],
  ['Press Pallof con carga', 'https://www.youtube.com/shorts/-HRPlwBXF9M'],
  ['salto al cajón rotacional sentado', 'https://www.youtube.com/watch?v=UZpiSfctuWw'],
  ['Salto al cajon Desde sentado', 'https://www.youtube.com/watch?v=HVsy1R7gt8U'],
  ['CM horizontal box jump', 'https://www.youtube.com/watch?v=06W3hU57IVU'],
  ['CM rotacional box jump', 'https://www.youtube.com/watch?v=CuLMFP2kBX4'],
  ['Bicho muerto 3 1', 'https://www.youtube.com/shorts/hcRjy_BNxO8'],
  ['Bicho muerto doble', 'https://www.youtube.com/shorts/3IMFivfo3gI'],
  ['Bicho muerto', 'https://www.youtube.com/shorts/TPx_P7EBnZo'],
  ['Flexion de brazos  reactivo', 'https://www.youtube.com/watch?v=2ub9reNjgNg'],
  ['Arm kb', 'https://www.youtube.com/shorts/KCCBZnEhr_g'],
  ['Plancha en fitball con impulso', 'https://www.youtube.com/shorts/zu11VKfX5kA'],
  ['Plancha con los codos extendidos', 'https://www.youtube.com/shorts/Oz2VOj4vLmY'],
  ['Halo', 'https://www.youtube.com/shorts/9f6KQNcPrEA'],
  ['Halo en cuclillas', 'https://www.youtube.com/shorts/Att1Mchm-Rs'],
  ['ISO push BB 1 leg squat', 'https://www.youtube.com/watch?v=XxXKljmq9j4'],
  ['Plancha Lateral Copenhague', 'https://www.youtube.com/watch?v=5huVNLKlQnQ'],
  ['Dragon Flag excéntrico', 'https://www.youtube.com/shorts/z9g-4e5UTP0'],
  ['2P CCM vertical asistido', 'https://www.youtube.com/watch?v=xN7raIceIkQ'],
  ['2P vercital CC reactivo', 'https://www.youtube.com/watch?v=K64HiFu3AHA'],
  ['Press pallof de anti extensión a anti lateral', 'https://www.youtube.com/watch?v=XqIiaVKmSzg'],
  ['Press pallof en estocada', 'https://www.youtube.com/watch?v=EO86EPfiXkY'],
  ['Estocada atras con mancuerna', 'https://www.youtube.com/watch?v=oFA1T7OvoSU'],
  ['Sentadilla frontal con elevacion de talon', 'https://www.youtube.com/watch?v=OaoFNb_F3IQ'],
  ['Elevacion en plancha lateral', 'https://www.youtube.com/shorts/dpryZWKBVSc'],
  ['Patada lateral gluteo', 'https://www.youtube.com/shorts/lbXXAnZXni8'],
  ['Posicion de sentadilla', 'https://www.youtube.com/shorts/No8E7k_5-ro'],
  ['8 kb', 'https://www.youtube.com/shorts/Io8R0Pc2Pt0'],
  ['Estiramiento dinamico cadena posterior', 'https://www.youtube.com/shorts/-DOSTI1kFLA'],
  ['Marcha de granjero unilateral', 'https://www.youtube.com/watch?v=g_t-T-crAlw'],
  ['Marcha de granjero', 'https://www.youtube.com/watch?v=75LbrFBc-y8'],
  ['Arranque dinamico con mancuerna', 'https://www.youtube.com/watch?v=R77y9sYLe-o'],
  ['Arranque con mancuerna', 'https://www.youtube.com/watch?v=nJDhyA9DxPk'],
  ['Estocada isometrica sobre disco', 'https://www.youtube.com/watch?v=jDTBN3yjGYc'],
  ['Estocada isometrica talon elevado', 'https://www.youtube.com/watch?v=cwMzToojrqM'],
  ['Rotaciones toracias 90 - 90', 'https://www.youtube.com/watch?v=3l5yNLDzZ1k'],
  ['remo en ladmine', 'https://www.youtube.com/shorts/9h_7xwd4aiQ'],
  ['Estiramiento de gluteo', 'https://www.youtube.com/shorts/EJBrL6qcRK8'],
  ['Curl de biceps en trx', 'https://www.youtube.com/shorts/IabNHY-0tx8'],
  ['Seal jack', 'https://www.youtube.com/shorts/lwmULyHsAsY'],
  ['Frog Pump', 'https://youtube.com/shorts/z7xN6HQqY4E'],
  ['Sentadilla a 1 pierna a cajon', 'https://www.youtube.com/shorts/Lx1sOSSb_Zo'],
  ['Sentadilla a 1 pierna pistol', 'https://www.youtube.com/shorts/wvUcsuXHzJY'],
  ['Movilidad de isquio con banda', 'https://www.youtube.com/shorts/g8KFFVJvo4I'],
  ['Abeduccion con banda', 'https://www.youtube.com/shorts/kyMqkLoAguQ'],
  ['Pull Apart', 'https://www.youtube.com/watch?v=XMxOYB3pMzk'],
  ['Regresion de peso muerto a 1 pierna', 'https://www.youtube.com/shorts/1wP0j2S47m8'],
  ['Peso muerto unipodal kb', 'https://www.youtube.com/shorts/2wx5eygff1s'],
  ['Mountain climbers', 'https://www.youtube.com/shorts/DNpRIm8OpSM'],
  ['Mountain climbers semi circle', 'https://www.youtube.com/shorts/74QKSV0A8NI'],
  ['In and out', 'https://www.youtube.com/shorts/rA5tAnR_z-Y'],
  ['Bisagra de Cadera con Bastón', 'https://youtube.com/shorts/08p594qtU0g'],
  ['Plancha jack', 'https://www.youtube.com/shorts/yFHvhdyYyfM'],
  ['clean and jerk ladmine', 'https://www.youtube.com/shorts/Zy-LnbEsYfM'],
  ['Arranque en ladmine', 'https://www.youtube.com/shorts/DHcMKNUrSJQ'],
  ['Peso muerto en ladmine', 'https://www.youtube.com/shorts/EHI09IuuI_c'],
  ['Remo en ladmine  toma vikinga', 'https://www.youtube.com/shorts/dVdXviu81WU'],
  ['Sentadilla en ladmine', 'https://www.youtube.com/shorts/1TH4bzE5RKk'],
  ['Press vikingo', 'https://www.youtube.com/shorts/hKU8gb9A6Tw'],
  ['Empuje de cadera con Abducción', 'https://www.youtube.com/watch?v=l7714O0l2mo'],
  ['Press pallof en estocada', 'https://www.youtube.com/shorts/_tfzBXjBSpE'],
  ['Press pallof mas skipping', 'https://www.youtube.com/shorts/W3op1ppSArs'],
  ['Bisagra de cadera en fitball', 'https://www.youtube.com/shorts/wgXeroA966A'],
  ['Regresion peso muerto unipodal', 'https://www.youtube.com/shorts/e_ogiYtZwq4'],
  ['Regresion peso muerto unipodal con band', 'https://www.youtube.com/shorts/eAIYrta4GP4'],
  ['Movilidad activa de isquio', 'https://www.youtube.com/shorts/2zujN5_VW78'],
  ['Estocada caminando enfoque en gluteo', 'https://www.youtube.com/shorts/NNuP5r95cp4'],
  ['Push press', 'https://www.youtube.com/shorts/RKPCtP2aAGc'],
  ['tall clean', 'https://www.youtube.com/shorts/YjTYMQQMJMw'],
  ['lateral hop', 'https://www.youtube.com/shorts/L2rANcis5BI'],
  ['skater jump al cajon', 'https://www.youtube.com/shorts/8kpQ-RLOUxs'],
  ['tall power jerk', 'https://www.youtube.com/shorts/zWbGLdQWHLU'],
  ['Movilidad de hombros en MB', 'https://www.youtube.com/shorts/xZr41kSeaEY'],
  ['Preventivo de espalda', 'https://www.youtube.com/shorts/yPU3bBYVO1g'],
  ['Movilidad de cadera 90/90', 'https://www.youtube.com/shorts/Fz66lHiIM6Q'],
  ['Salto con banda de resistencia', 'https://www.youtube.com/shorts/gbdn62JBsaE'],
  ['Salto lateral + salto al cajon', 'https://www.youtube.com/shorts/AsWt4ZHZHGI'],
  ['Split jump + salto al cajon', 'https://www.youtube.com/shorts/m1c8Pde4054'],
  ['Dominadas a un brazo', 'https://www.youtube.com/shorts/xle5NRYu3Qw'],
  ['Seal row', 'https://www.youtube.com/shorts/9XY6_yCT8nA'],
  ['Core en puente', 'https://www.youtube.com/shorts/ujYxa-rTKww'],
  ['Dominadas prono', 'https://www.youtube.com/shorts/W801Dc3xjd8'],
  ['Dominadas tras nuca', 'https://www.youtube.com/shorts/6igEb2coIAE'],
  ['Dragon flag leg', 'https://www.youtube.com/shorts/KRli1_XK2oA'],
  ['Dragon flag truck', 'https://www.youtube.com/shorts/mX6jDHLxw90'],
  ['Drafon flag negative', 'https://www.youtube.com/shorts/DobyFAKJiqY'],
  ['Dragon flag pulso', 'https://www.youtube.com/shorts/UziMFKUi6gk'],
  ['Swing T handle', 'https://www.youtube.com/shorts/VeQ61u-FRS8'],
  ['Peso muerto toma de arranque', 'https://www.youtube.com/shorts/yZnvLlXeSzg'],
  ['Stradle lift', 'https://www.youtube.com/shorts/het9cgBX6ko'],
  ['Aperturas de pecho en TRX', 'https://www.youtube.com/shorts/VA6kRuwZZdw'],
  ['Press pecho en TRX', 'https://www.youtube.com/shorts/iBF3_Vz0uRA'],
  ['Press frances en TRX', 'https://www.youtube.com/shorts/lP54jXOGgRg'],
  ['Curl femoral en TRX', 'https://www.youtube.com/shorts/rVS70fc_Z2I'],
  ['Plancha dinamica supina', 'https://www.youtube.com/watch?v=PR-vF7gRZ6E'],
  ['Plancha supina', 'https://www.youtube.com/watch?v=8z_5hyGyucM'],
  ['Plancha alta supina', 'https://www.youtube.com/watch?v=BE5NaeaRp8k'],
  ['Plancha baja supina', 'https://www.youtube.com/watch?v=CAqdjbbigZA'],
  ['Press de banco con mancuernas', 'https://www.youtube.com/watch?v=DxcaP3hlAig'],
  ['Empuje de cadera a una pierna mas press', 'https://www.youtube.com/watch?v=JlADhpp9570'],
  ['Empuje de cadera mas press', 'https://www.youtube.com/watch?v=qLu1oyPFlGg'],
  ['Press z dumbell', 'https://www.youtube.com/watch?v=L4XivO1S9b4'],
  ['Plancha quito apoyos', 'https://www.youtube.com/watch?v=AGR-iYTSqrE'],
  ['Plancha toque de hombros', 'https://www.youtube.com/watch?v=pfrPrKRfmaU'],
  ['Plancha mas empuje', 'https://www.youtube.com/watch?v=KlrOpscVXRI'],
  ['Plancha lateral + remo', 'https://www.youtube.com/watch?v=dhgb3aksXK8'],
  ['Plancha alta + traslado', 'https://www.youtube.com/watch?v=MH8DI3Ic0uE'],
  ['Plancha posicion de oso + traslado', 'https://www.youtube.com/watch?v=K9HJDBYTE1c'],
  ['Swing de la cabra kb', 'https://www.youtube.com/watch?v=Foexdlb-W24'],
  ['Vuelos frontal con disco', 'https://www.youtube.com/watch?v=XDfSUSLZTUk'],
  ['Vuelos frontales con mancuerna', 'https://www.youtube.com/watch?v=RF3zt95t_Mk'],
  ['Vuelos laterales', 'https://www.youtube.com/watch?v=mFvAdb8VTuk'],
  ['Plancha lateral gluteo medio', 'https://www.youtube.com/watch?v=_RtHS0oE0wA'],
  ['Fondos en banco regresion', 'https://www.youtube.com/watch?v=07fiXsI4ofU'],
  ['Larseen press', 'https://www.youtube.com/watch?v=TJeV0wbChR0'],
  ['Frog pump', 'https://www.youtube.com/watch?v=Ys5eFYCBbJw'],
  ['Elevacion de cadera elevado kb', 'https://www.youtube.com/watch?v=3NOzET3GxQo'],
  ['Elevacion de cadera unipodal elevado', 'https://www.youtube.com/watch?v=G5BzqWfAxFk'],
  ['Empuje de cadera con banda', 'https://www.youtube.com/watch?v=ig3Zh7x9boo'],
  ['Peso muerto piernas rigidas', 'https://www.youtube.com/watch?v=6u-HUt57r0I'],
  ['Cargada de potencia colgado', 'https://www.youtube.com/watch?v=ZRiMSarGUmU'],
  ['Envion de potencia', 'https://www.youtube.com/watch?v=TF_ENOxaIYM'],
  ['Salto vertcal con banda de resistencia', 'https://www.youtube.com/watch?v=cnrWAdgzxu0'],
  ['Movilidad dinamica de isquio en un apoyo', 'https://www.youtube.com/watch?v=aS7pv9bRGi0'],
  ['Plancha copenhague', 'https://www.youtube.com/watch?v=hR_2qQKH34c'],
  ['Plancha copenhague regresion', 'https://www.youtube.com/watch?v=F7o2l4vRAj4'],
  ['Camino a la plancha', 'https://www.youtube.com/watch?v=j1yuLZvI8zM'],
  ['Plancha lateral aductor', 'https://www.youtube.com/watch?v=esZNWNyMfOU'],
  ['Masaje foam roll aductor', 'https://www.youtube.com/watch?v=QzSm7jhfxCM'],
  ['Masaje foam roll tensor de la fascia', 'https://www.youtube.com/watch?v=5Vyq1iPYJSM'],
  ['Masaje foam roll isquio', 'https://www.youtube.com/shorts/GhykjnVLKLk'],
  ['Bicho muerto con disco', 'https://www.youtube.com/watch?v=Q0bfCT5BrkI'],
  ['Bicho muriendo con disco', 'https://www.youtube.com/watch?v=Tw-RxQw8Jlk'],
  ['Gemelos con barra', 'https://www.youtube.com/shorts/kU2Z8TbALvo'],
  ['Patron respiratorio posicion bebe', 'https://www.youtube.com/shorts/V7YiLkkCWyc'],
  ['Patron respiratorio progresion', 'https://www.youtube.com/shorts/vtpCfVMsP6g'],
  ['Patron respirstorio acostado', 'https://www.youtube.com/shorts/2Byu1a7mM68'],
  ['Bisagra de cadera', 'https://www.youtube.com/shorts/XpbFoRtvTrs'],
  ['Hiperextension de cadera prono', 'https://www.youtube.com/shorts/CQf7a8dDsA0'],
  ['Puente bilateral con tension', 'https://www.youtube.com/shorts/ymr5TqoSeBU'],
  ['Remo en dos apoyos', 'https://www.youtube.com/watch?v=eC78VGGlmmU'],
  ['Remo invertido a 45 supino', 'https://www.youtube.com/watch?v=k7j3dkXyBA8'],
  ['Remo prono regresion', 'https://www.youtube.com/watch?v=psdkDu3f6h8'],
  ['Remo invertido prono', 'https://www.youtube.com/watch?v=mUhI-eF8t-4'],
  ['Remo invertido sobre cajon', 'https://www.youtube.com/watch?v=vIXCE7DsgOo'],
  ['Remo con banda unilateral', 'https://www.youtube.com/watch?v=l1GxZ3usiOM'],
  ['Curl de biceps alternados', 'https://www.youtube.com/watch?v=sXTlo_qbUUs'],
  ['curl de biceps martillo', 'https://www.youtube.com/watch?v=NssBpIn9D44'],
  ['Remo con barra toma prono', 'https://www.youtube.com/watch?v=Ba_9X2DVDng'],
  ['Remo con barra toma supina', 'https://www.youtube.com/watch?v=Nx8STiajoDo'],
  ['Curl de bicpes con barra', 'https://www.youtube.com/watch?v=c7s6b8MmA5Q'],
  ['Acoples paralelos', 'https://www.youtube.com/shorts/9z6Ufe-nAbs'],
  ['Curl de isquio excentrico', 'https://www.youtube.com/shorts/0dRScbPffdE'],
  ['Levantada turca con kb', 'https://www.youtube.com/shorts/4OV-6B3PP4I'],
  ['Hike pass mas swing', 'https://www.youtube.com/shorts/eQO2GvcRwfs'],
  ['Hike pass kb', 'https://www.youtube.com/shorts/sr-zta1I1Kg'],
  ['BK clean pause', 'https://www.youtube.com/shorts/DOeFn_jTOGE'],
  ['Cat cow', 'https://www.youtube.com/shorts/n4InZXtYr0I'],
  ['Split jump +  salto al cajon', 'https://www.youtube.com/shorts/m1c8Pde4054'],
  ['Impulso mas salto al cajon', 'https://www.youtube.com/shorts/XQXVDoKeVLA'],
  ['Recepcion lateral mas salto', 'https://www.youtube.com/shorts/ypwIYoNaHhI'],
  ['Salto a una pierna', 'https://www.youtube.com/shorts/I7Z1o0b_IAk'],
  ['Clean con kb', 'https://www.youtube.com/shorts/MPo5913e9_U'],
  ['Swing frontal', 'https://www.youtube.com/shorts/q8HOtc2BcaM'],
  ['Patrones rotacionales kb', 'https://www.youtube.com/shorts/FF2hBhWJJi8'],
  ['Progresion roll out', 'https://www.youtube.com/shorts/s7vHMxpzm0o'],
  ['Roll out declinado', 'https://www.youtube.com/shorts/GbKwpqmXMwg'],
  ['Roll out con fitball', 'https://www.youtube.com/shorts/7NM0KPZUSQ8'],
  ['Tgu con mancuerna', 'https://www.youtube.com/shorts/iIiBwgfz1k0'],
  ['Movilidad de tobillo sobre cajon', 'https://www.youtube.com/shorts/O9ypxkebUNM'],
  ['Molino alto', 'https://www.youtube.com/shorts/-7bS0rFaqz4'],
  ['Molino completo', 'https://www.youtube.com/shorts/ElOVEBSkToY'],
  ['Salto con carga', 'https://www.youtube.com/watch?v=j7cLFbCb4WQ'],
  ['Lanzamiento MB Horizontal', 'https://www.youtube.com/watch?v=MelxJ6fIrIE'],
  ['Lanzamiento frontal arrodillado MB', 'https://www.youtube.com/watch?v=Z3VRyXV2NV0'],
  ['Lanzamiento rotacional MB', 'https://www.youtube.com/watch?v=sVXRGrl_lOs'],
  ['Lanzamiento bisagras MB', 'https://www.youtube.com/watch?v=49HyGBQt06k'],
  ['Halo mas bisagras con disco', 'https://www.youtube.com/watch?v=ciDq5EEBpXA'],
  ['Movilidad de hombros con banda', 'https://www.youtube.com/watch?v=kRcdXYADjVI'],
  ['giros rusos', 'https://www.youtube.com/watch?v=yzs5aSLXqrU'],
  ['Abdominales con carga', 'https://www.youtube.com/watch?v=DhWXh2T5WDc'],
  ['Hollow dinamico', 'https://www.youtube.com/watch?v=ES50-ij_-IQ'],
  ['Remo a un brazo pelvis alineada', 'https://www.youtube.com/watch?v=DCq0BWHVhGc'],
  ['Remo a un brazo sobre banco', 'https://www.youtube.com/watch?v=CkYq4p1ZGUc'],
  ['Press militar posicion de caballero', 'https://www.youtube.com/watch?v=QgmWP4XrWzQ'],
  ['Press militar posicion dividida', 'https://www.youtube.com/watch?v=K843GL4NhE4'],
  ['Press militar alternado', 'https://www.youtube.com/watch?v=K843GL4NhE4'],
  ['Exension isometrica en banco rumano', 'https://www.youtube.com/shorts/UiUZUzFCBQc'],
  ['Cars de cadera', 'https://www.youtube.com/shorts/GoNL5OKdNE4'],
  ['Sentadilla isometrica a una pierna', 'https://www.youtube.com/watch?v=U5aTbn31AdA'],
  ['Sentadilla isometrica', 'https://www.youtube.com/watch?v=8ryYxOP-tEw'],
  ['Plancha prona en 3 apoyos', 'https://www.youtube.com/shorts/VaPSLneKW3w'],
  ['Cars de tobillo', 'https://www.youtube.com/shorts/Bjmj4j2Ksws'],
  ['Cars de columna', 'https://www.youtube.com/shorts/xq-aAx71TD0'],
  ['Sentadilla frontal asimetrica', 'https://www.youtube.com/shorts/ABB1YAzKPAQ'],
  ['Remo pendlay', 'https://www.youtube.com/shorts/6XCpd2Ti5Mw'],
  ['Estocadas con barra', 'https://www.youtube.com/shorts/8wCvGSXi1nM'],
  ['Curl de biceps con barra EZ', 'https://www.youtube.com/shorts/l_AyyuAjiBo'],
  ['Subidas al cajon a una pierna', 'https://www.youtube.com/shorts/pWD5Z7ZNEt8'],
  ['Marcha granjero zercher', 'https://www.youtube.com/shorts/aA1HjDjOK0s'],
  ['Flexion extension de tobillo', 'https://youtube.com/shorts/7UfHvAa8uxE'],
  ['Rotacion interna de tobillo', 'https://www.youtube.com/shorts/7UfHvAa8uxE'],
  ['Gato contento-enojado de tobillo', 'https://www.youtube.com/shorts/hSVZdorfEjk'],
  ['Rotacion externa de hombro', 'https://www.youtube.com/shorts/7cOzTSb6_6A'],
  ['Face pull', 'https://www.youtube.com/shorts/B-wG2_D_6Dk'],
  ['Curl de Isquio en maquina', 'https://www.youtube.com/watch?v=r1mpa9MzhbA'],
  ['Curl de isquio en maquina', 'https://www.youtube.com/watch?v=r1mpa9MzhbA'],
  ['Curl nordico', 'https://www.youtube.com/watch?v=Eifq68P1_cI'],
  ['Step up excentrico', 'https://www.youtube.com/watch?v=FXdUx8LECVc'],
  ['Hip Thrust', 'https://www.youtube.com/watch?v=vcfhPJXIHx0'],
  ['Puente isquio', 'https://www.youtube.com/watch?v=a6xV7Dm35Eo'],
  ['Sentadilla bulgara', 'https://youtu.be/CIOSvXPyNog'],
  ['CMJ', 'https://www.youtube.com/watch?v=7Fh_l1VBoZk'],
  ['Sprint', 'https://www.youtube.com/watch?v=I90IazvXpKY'],
];

function normalize(s) {
  return s.toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '') // remove accents
    .replace(/\s+/g, ' ')
    .trim();
}

async function main() {
  const ejercicios = await prisma.ejercicio.findMany({ select: { id: true, nombre: true, videoUrl: true } });
  console.log(`Total ejercicios en DB: ${ejercicios.length}`);

  let updated = 0;
  let notFound = [];

  for (const [nombre, url] of VIDEOS) {
    const normBuscar = normalize(nombre);

    // Try exact match first (normalized)
    let match = ejercicios.find(e => normalize(e.nombre) === normBuscar);

    // If not found, try contains
    if (!match) {
      match = ejercicios.find(e => normalize(e.nombre).includes(normBuscar) || normBuscar.includes(normalize(e.nombre)));
    }

    if (match) {
      if (match.videoUrl !== url) {
        await prisma.ejercicio.update({ where: { id: match.id }, data: { videoUrl: url } });
        updated++;
        console.log(`✓ ${match.nombre}`);
      }
    } else {
      notFound.push(nombre);
    }
  }

  console.log(`\n✅ Actualizados: ${updated}`);
  if (notFound.length > 0) {
    console.log(`\n⚠ No encontrados (${notFound.length}):`);
    notFound.forEach(n => console.log(`  - ${n}`));
  }

  await prisma.$disconnect();
  await pool.end();
}

main().catch(e => { console.error(e); process.exit(1); });